stages:
  - build
  - image

build_project:
  image: golang:latest
  stage: build
  script:
    - go get github.com/constabulary/gb/...
    - ln -s /builds /go/src/gitlab.com
    - cd /go/src/gitlab.com/${CI_PROJECT_PATH}
    - GOOS=linux GOARCH=amd64 CGO=0 gb build -ldflags '-w -s -extldflags "-static"'
    - mv bin/blackhole-linux-amd64 bin/blackhole
  artifacts:
    paths:
      - bin/blackhole
  cache:
    paths:
      - bin/blackhole

build_docker_image:
  image: jonaskello/docker-and-compose:17.03.0-1.18.0
  stage: image
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:17.03.0-dind
  script:
    - cd /builds/${CI_PROJECT_PATH}
    - cp /etc/ssl/certs/ca-certificates.crt ca-certificates.crt
    - docker login https://${HUB_URL} -u ${HUB_LOGIN} -p ${HUB_PASSWORD}
    - docker build -t ${HUB_URL}/godns:latest .
    - docker push ${HUB_URL}/godns

